DEFAULT_dataset = "data/dataset.xyz"
DEFAULT_batch_size = 20
DEFAULT_dt = 0.1 
DEFAULT_learning_rate = 1.0e-05
DEFAULT_epochs = 5 #10 
DEFAULT_prefactor = 1.0
DEFAULT_jacobi_prefactor = 1.0
DEFAULT_neurons = 64
DEFAULT_layers = 2
DEFAULT_folder_name = "."
